@startuml System_Sequence_Diagrams_external

'Dichiarazione degli attori e partecipanti
actor User

participant Generator
participant Dictionary
participant TemplatesLibrary
participant Template
participant Analyzer
participant Moderator

'Prima parte del grafico
== Text analysis and new token insertion into dictionaries ==
User -> Generator: Enter sentence
activate Generator
Generator -> Analyzer: Ask to analyze
activate Analyzer
Analyzer --> Generator: Return tokens
deactivate Analyzer
Generator -> Dictionary: Save new words
activate Dictionary
Dictionary --> Generator: Return
deactivate Dictionary

'Seconda parte del grafico
== Building a no sense random sentence==
Generator -> TemplatesLibrary: Request Template
activate TemplatesLibrary
TemplatesLibrary --> Generator: Return Template
deactivate TemplatesLibrary

loop end when you have filled every type of token list
Generator -> Template: fillTokenList(Token t)
activate Template
Template -> Dictionary: getToken
activate Dictionary
Dictionary -> Template: return Token t
deactivate Dictionary
deactivate Template
end

Generator -> Generator: shuffle every token list

Generator --> Templates : fill the template
activate Templates
Templates --> Generator: return Sentence
deactivate Templates

== Checking Toxicity ==
Generator -> Moderator: Ask to analyze toxicity
activate Moderator
alt check toxicity
    Moderator --> Generator: [Return unacceptable toxicity]
    Generator --> User: [Return unacceptable toxicity]
else
    Moderator --> Generator: [Return acceptable toxicity]
    deactivate Moderator
    Generator --> User: Return the sentence
    deactivate Generator
end


@enduml