@startuml
participant Generator
participant Analyzer
participant GoogleLanguageAPI

Generator -> Analyzer : analyzeSentence(sentenceIn)
Analyzer -> GoogleLanguageAPI : LanguageApi(sentenceIn)
GoogleLanguageAPI -> Analyzer : API Response

Analyzer -> Analyzer : getNouns()
Analyzer -> Generator : nounList.addAll(getNouns())

Analyzer -> Analyzer : getAdj()
Analyzer -> Generator : adjList.addAll(getAdj())

Analyzer -> Analyzer : getVerbs()
Analyzer -> Generator : verbList_nothirdperson.addAll(getVerbs())

Analyzer -> Analyzer : getVerbs_thirdperson()
Analyzer -> Generator : verbList.addAll(getVerbs_thirdperson())

Analyzer -> Analyzer : getVerbs_past()
Analyzer -> Generator : verbList_past.addAll(getVerbs_past())

@enduml
