@startuml InternalFillTemplate

!include Graphic.puml

participant Generator
participant Template as Templates

activate Generator
Generator -> Templates: FillTemplate(List<MyNoun> nouns, List<MyVerb> verbs, List<MyVerb> verbs_nothirdperson, List<MyAdjective> adjectives)
activate Templates

Templates->Templates: Check if number of tokens is correct
Templates->Templates: Check if we need to use third or no-third person

loop foreach (noun) in Template
    Templates ->Templates: Replace (noun) with nouns.get(i).toString()
end

loop foreach (verb) in Template
    alt nothirdperson == true
    Templates ->Templates: Replace (verb) with verbs_nothirdperson.get(i).toString()
    else nothirdperson == false
    Templates ->Templates: Replace (verb) with verbs.get(i).toString()
    end
end   

loop foreach (adj) in Template
    Templates ->Templates: Replace (adj) with adj.get(i).toString()
end   

Templates --> Generator: return Sentence 
deactivate Templates

deactivate Generator

@enduml